# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
collections:
  achieves:
  books:
# Setup
title:               블로그 수정중
tagline:             'Currently making blog'
description:         'Made by <a href="https://github.com/gogoymh" target="_blank" style="font-size=0.75rem;">@gogoymh</a>.<br />블로그 수정중'
github-url:           http://github.com/gogoymh
baseurl:             ''
plugins:             [jekyll-paginate]
paginate:            5
regenerate :         true

# About/contact
author:
  name:              Minhyeong Yu
  url:               
  email:             12ymh12@gmail.com

# Custom vars
version:             1.0.0

# Highlighter
highlighter: rouge
