# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
collections:
  achieves:
  books:
# Setup
title:               블로그 테스트
tagline:             'List Of What I Learned'
description:         'Made by <a href="https://github.com/gogoymh" target="_blank" style="font-size=0.75rem;">@Byun Kyung Min</a>.<br />블로그 테스트'
github-url:           http://github.com/gogoymh
baseurl:             ''
plugins:             [jekyll-paginate]
paginate:            5
regenerate :         true

# About/contact
author:
  name:              Byun Kyung Min
  url:               https://facebook.com/bkm.change.min
  email:             bkm.change.min@gmail.com

# Custom vars
version:             1.0.0

# Highlighter
highlighter: rouge
