# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               변경민의 LOWIL
tagline:             'List Of What I Learned'
description:         'Made by <a href="https://github.com/changemin" target="_blank">@Byun Kyung Min</a>.<br />한국디지털미디어고등학교 18기 웹프로그래밍과 변경민'
github-url:           http://github.com/Changemin
# baseurl:             '/'
plugins:             [jekyll-paginate]
paginate:            5
regenerate :      true

# About/contact
author:
  name:              Byun Kyung Min
  url:               https://facebook.com/bkm.change.min
  email:             bkm.change.min@gmail.com

# Custom vars
version:             1.0.0
